<?php

// Generating: For each Table a checker-function
//
// library: mysqli
// Ubuntu: sudo apt-get install php-mysqlnd
//


// Create the script
function generationFoo() {

	////
	// First connect to the database and get all table names
	////
	
	$host = "localhost:3306";
	$user = 'ilias';
	$password = "dbpass";
	$database = "information_schema";


	// Connection to Database
	$conn = new mysqli($host, $user, $password, $database);

	// Check connection
	if ($conn->connect_error) {
    		die("Connection to database failed: " . $conn->connect_error);
	}

	////
	// Printing all Tablenames
	////
	$tablename="COLUMNS";


	$query="SELECT TABLE_NAME FROM $tablename WHERE TABLE_SCHEMA = 'ilias' AND COLUMN_NAME = 'obj_id'";

	$result = $conn->query($query);
	//
	//
	//
	if ($result) {
	
		// Saves each tablename in array: result_array
    		while ($row = $result->fetch_assoc()) {
    		$result_array[] = $row['TABLE_NAME'];
		}
	
	} else {
		// Error message, if there is an error
		echo "Error while request: " . $conn->error;
		
	}
	
	
	$result->close();
	// Closing connection to database
	$conn->close();
	
	//Checks if the script is already existing
	$script_file_exists = file_exists('check_tables_generated.php');
	if ($script_file_exists) {
        	 $existingScript= file_get_contents('check_tables_generated.php');
        }
	
	
	// Starting generation a script
	$scriptContent = "<?php\n";
	
	////
	// Generation for each table a function to check
	///
	
	
	$scriptContent .= "////\n";
	$scriptContent .= "// Generated script with index.php\n";
	$scriptContent .= "// Check for each table in the database\n";
	$scriptContent .= "////\n\n\n";
	$scriptContent .= "//Complete result \n";
	$scriptContent .= '$complete_result = array();'."\n\n";
	$functionCalls = [];
	
	if($script_file_exists){
		$scriptContent .= checkAutoGeneratedFunctions($existingScript);
		foreach ($result_array as $tableName) {
			$functionCalls[] = "check_$tableName";
		}
	
	}else{
		$scriptContent .= "////\n";
		$scriptContent .= "//Custome area start\n\n";
		$scriptContent .= "//Custome area end\n";
		$scriptContent .= "////\n\n\n";
		foreach ($result_array as $tableName) {
			$scriptContent .= generateFunctionForTable($tableName);
			$functionCalls[] = "check_$tableName";
			}	
		
		}
	
		// main-function
		$scriptContent .= "// main function to call all generated functions\n";
		$scriptContent .= "function main() {\n";
		if($functionCalls != null) {
			foreach ($functionCalls as $functionCall) {
        			$scriptContent .= "    {$functionCall}();\n";
    			}
		}	
    	
    	$scriptContent .= "}\n\n";
    	$scriptContent .= "// Call main-function\n";
    	$scriptContent .= "main();\n";
    	
	$scriptContent .= "// Clear text-file for new information"."\n";
	$scriptContent .= 'file_put_contents("problematic_tables_obj.txt", \'\');'."\n";
	$scriptContent .= '$iteration = 0;'."\n";
	$scriptContent .= 'foreach ($complete_result as $file_object) {'."\n";
	$scriptContent .= '	//print_r($complete_result[$iteration][\'Objects\']);'."\n";
	$scriptContent .= '	$data = json_encode($file_object, JSON_PRETTY_PRINT);'."\n";
	$scriptContent .= '	file_put_contents("problematic_tables_obj.txt", $data, FILE_APPEND);' ."\n";
	$scriptContent .= '	$iteration++;'."\n";
	$scriptContent .= '}'."\n\n";
	$scriptContent .= "////\n";
	$scriptContent .= "////\n";
	$scriptContent .= "// END of script\n";
	$scriptContent .= "////\n";
	$scriptContent .= "////\n";
	$scriptContent .= "?>";
	
	// Save generated script
	file_put_contents('check_tables_generated.php', $scriptContent);
	
}

// Function to generate an autogenerated function for a table in the database
function generateFunctionForTable($tableName){
		$temp_scriptContent = "// Start of autogenerated function for table $tableName\n";
		$body_scriptContent = "function check_$tableName() {\n";
		$body_scriptContent .= '	global $complete_result;'."\n";
		$body_scriptContent .= "	// Call the tool with a tablename\n";
		$body_scriptContent .= '	require_once "tool_referentielle_integritaet.php";'."\n";
		$body_scriptContent .= "	// Gets the result-array of the other script\n";
		$body_scriptContent .= '	$result_temp ' ."= checkMistakesinTables('$tableName', 'object_data', 'obj_id');\n";
		$body_scriptContent .= '	if ($result_temp[0] > 0) {'."\n";
		//$body_scriptContent .= '	echo "Object_IDs of table " .'."$tableName .:".'\n;'."\n";
		//$body_scriptContent .= '	for($i = 0; $i < count($result_temp); $i++){'."\n";
		//$body_scriptContent .= '		echo "\n" .$result_temp[$i];'."\n";
		//$body_scriptContent .= "	}";."\n"
		//$body_scriptContent .= "		// Results which are stored together"."\n";
		//$body_scriptContent .= '		$obj_results += $result_temp;'."\n";
		$body_scriptContent .= "		// Stores the complete Results: Tables with problematic objects"."\n";
		$body_scriptContent .= '		$complete_result[] = array("Table" => '.'"'."$tableName".'"'.', "Objects" => $result_temp);'."\n";
		$body_scriptContent .= "	}\n";
		$body_scriptContent .= "}\n\n";
		$temp_scriptContent .= $body_scriptContent;
		$temp_scriptContent .= "// End /*";
		
		$hash_sum = md5($body_scriptContent);
		$temp_scriptContent .= ": $hash_sum";
		$temp_scriptContent .= "*/\n\n";
		
		return $temp_scriptContent;
}

// Checks the functions
function checkAutoGeneratedFunctions($existingScript){    

	//custome area pattern
	$custome_area_pattern = '/\/\/\/\/\R\/\/Custome area start\R(.*?)\R\/\/Custome area end\R\/\/\/\//s';
	
	
	//get custome area 
	preg_match_all($custome_area_pattern, $existingScript, $value_custome_area, PREG_SET_ORDER);
	
	$new_scriptContent = "";
	foreach($value_custome_area as $area) {
		$new_scriptContent .= $area[0];
	
	}
	
	$new_scriptContent .= "\n\n\n";
		
	 	
	//regex for searching
	$pattern ='/\/\/ Start of autogenerated function for table (\w+)\R(.*?)\R\/\/ End \/\*(.*?)\*\//s';
	//search for pattern in existing file
	preg_match_all($pattern, $existingScript, $matches, PREG_SET_ORDER);
	
	foreach($matches as $match) {
	
		// get tablename
		$tableName = $match[1];
		
		// Body part between Start and End
		$body_content = $match[2];
		
		//hash of body
		$hash_sum = md5($body_content);
		
		//Get hash after End
		$given_hash = $match[3];
		
		if($hash_sum === $given_hash) {
			
			//overwrite old code
			$new_scriptContent .= generateFunctionForTable($tableName);
		} else {
			$new_scriptContent .= $match[0];
		}
	}
	
	return $new_scriptContent;
    
}

// Call function generationFoo
echo "Start generating\n";
generationFoo();
echo "END generating\n";
?>
